
import Link from "next/link";
import React, { useEffect } from "react";

const MoleculeInfo = ({ molecules }) => {
  useEffect(() => {
    // Apply SMILES to image transformation code whenever page changes
    if (window.SmiDrawer) {
      window.SmiDrawer.apply();
    }
  }, [molecules]);

  return (
    <>
      {molecules.map((molecule) => (
        <Link key={molecule.moleculeId} href={`/molecule/${molecule.moleculeId}`} >
          <div className="p-3 gap-2 my-1 rounded-xl border-[1px] border-zinc-600 w-3/4">
            <div>
              {/* The images will be generated by the SMILES to image transformation script */}
              <img
                data-smiles={molecule.structure.SMILES}
                data-smiles-options={JSON.stringify({ width: 500, height: 500 })}
                alt="Molecule"
              />
            </div>
            <div className="flex-col gap-2">
              <div className=" flex text-xl font-semibold">{molecule.name}</div>
              <span className="text-lg font-light">Origin: {molecule.origin.kingdom}, {molecule.origin.genus}, {molecule.origin.species}</span>
            </div>
          </div>
        </Link>

      ))}
    </>
  );
};

export default MoleculeInfo;
