
"use client";
import React, { useEffect } from "react";

const MoleculeRecord = ({ molecule }) => {
  useEffect(() => {
    // Apply SMILES to image transformation code whenever page changes
    if (window.SmiDrawer) {
      window.SmiDrawer.apply();
    }
  }, [molecule]);

  return (
    <div>
      <div className="rounded-xl border-[2px] border-zinc-600 w-full">
        <div>
          {/* The images will be generated by the SMILES to image transformation script */}
          <img
            data-smiles={molecule.structure.SMILES}
            data-smiles-options={JSON.stringify({ width: 500, height: 500 })}
            alt={`Molecule ${molecule.moleculeId}`}
          />
        </div>
        <div className="gap-2">
          <div className="flex text-xl font-semibold">{molecule.name}</div>
          <span className="text-lg font-light">ID: {molecule.moleculeId}</span>
          <span className="text-lg font-light">
            Origin: {molecule.origin.kingdom}, {molecule.origin.genus}, {molecule.origin.species}
          </span>
          <span className="text-lg font-light">
            First Literature Report: {molecule.metadata.journal}, {molecule.metadata.reference}, {molecule.metadata.year}, {molecule.metadata.doi}
          </span>
          <span className="text-lg font-light">
            Location of Extraction: {molecule.location.state}, {molecule.location.site}
          </span>
          <span className="text-lg font-light">
            Known Bioactivities: {molecule.bioactivity && molecule.bioactivity.activity_1 !== null ? molecule.bioactivity.activity_1 : ''}
          </span>
        </div>
      </div>
    </div>
  )

};

export default MoleculeRecord;